# Generated by Django 2.1.1 on 2018-09-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='fotka',
            field=models.ImageField(blank=True, null=True, upload_to='Pizza.Pizzafotka/media'),
        ),
    ]
